---
title: "PS9 lite: Linear regression via linear algebra"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(knitr)
```


## Your work

1. You will make one submission to Kaggle using Random Forests using any method of your choice.
1. This problem is very short and straightforward, so there will be no groups. 
1. Also, to minimize cognitive load, you will use the same data and model formula as in PS7 on LASSO.


## What's due when?

1. By **Friday 4/24 9pm Eastern** (note evening due time) you must submit all your work on GitHub.
1. However instead of submiting work as you have been until now, we're going to practice the "GitHub Pull Request" flow. This is how open source collaboration on GitHub works. Watch this [6min screencast](https://www.loom.com/share/88b00641608f49bab411d06903303355) to see how.
1. Remember: you work is not considered submitted until your pull request shows up [here](https://github.com/293-2020-01-Fall/PS8lite/pulls)


## Evaluation criteria

1. **"If others can't reproduce your work, they will throw it in the trash."** Submissions that don't knit will be penalized harshly. 
1. **"Presentation and communication-style matters."** Related to point above, for example
    + Plots: Keep the "ink-to-information" ratio in mind. Ensure your plots have labeled axes and informative titles.
    + Use markdown formatting to make your presentation effective.
    + Is code cleanly written, well-documented, and well-formatted. As the semester progresses, I'll be giving feedback from [The tidyverse style guide](https://style.tidyverse.org/).
1. As long as you make one valid submission to Kaggle using any Random Forest, you are good. 
